exp_name: debug
seed: 67

diffusion_config:
  ema_power: 0.75
  ema_update_after_step: 0
  learning_rate: !!float 1e-4
  lr_warmup_percentage: 0.1
  warmup_min_lr_ratio: 0.1
  min_lr_ratio: !!float 1e-3
  acc_threshold: 0.01

  l_simple_weight: !!float 1.0
  l_vlb_weight: !!float 1e-3

  min_snr_weighting: true
  min_snr_gamma: 5.0

train_dataset_config:
  csv_path: 'data/grippers/data.csv'
  object_encoder_name: placeholder
  max_cond_obj: 1
  dl_alpha: 20.0
  dl_eps: !!float 1e-6
  gripper_dir: data/grippers/
  gripper_per_sample: 100
  sample_mode: random
val_dataset_config:
  csv_path: 'data/grippers/data.csv'
  object_encoder_name: placeholder
  max_cond_obj: 1
  dl_alpha: 25.0
  dl_eps: !!float 1e-6
  gripper_dir: data/grippers/
  gripper_per_sample: 25
  sample_mode: top

gripper_config:
  num_fingers: 4
  max_num_segments: 10
  gripper_dim: 10

callbacks_config:
  RichProgressBar:
    leave: true
  LearningRateMonitor:
    logging_interval: step
  ModelCheckpoint:
    filename: 'epoch_{epoch:03d}_finalsampleloss_{val/final_sample_loss:.4f}_noisepredloss_{val/noise_pred_loss:.4f}_acc_{val/accuracy:.4f}'
    every_n_epochs: 1
    save_last: true
    save_top_k: 5
    monitor: "val/final_sample_loss"
    mode: min
    save_weights_only: false
    auto_insert_metric_name: false
  DeviceStatsMonitor: {}
  EarlyStopping:
    monitor: "val/final_sample_loss"
    min_delta: 0.0
    patience: 250
    verbose: false
    mode: min

logger_type: ['tensorboard','csv']
gpus: [1]
check_val_every_n_epoch: 5
log_every_n_steps: 1
max_epochs: 10000
default_root_dir: 'training_logs/'
gradient_clip_val: !!float 1.0
gradient_clip_algorithm: norm
num_sanity_val_steps: 2

dl_total_batch_size: 1
dl_micro_batch_size: 1
dl_num_workers: 4

noise_pred_net: gripper_rep
diffusion_type: custom_finger_diffusion


