out_dir: ./local/debug/test
env_config_file: gripping_env.yaml
save_every_iter: 1
render_every_iter: 1
n_iters: 301
n_frames: 100

controller_type: all_on
action_v_strength: 0.3

loss_types: [GrippingObjectLoss]
obj_particle_id: 2
obj_initial_pos: [0.55, 0.4, 0.4]

seed: 100
torch_seed: 100
static_as_fixed: True
device_memory_fraction: 0.75

optimize_designer: True
optimize_design_types: ['geometry']
designer_lr: 0.1
gen_pointe_bounding_box:
  max: [0.5,0.5,0.5]
  mean: [0.,0.,0.]
  min: [-0.5,-0.5,-0.5]