out_dir: ./local/gripping_v0/gripping_env-100
env_config_file: gripping_env.yaml
save_every_iter: 1
render_every_iter: 1
n_iters: 301
n_frames: 200

controller_type: all_on
action_v_strength: 0.3

loss_types: [ThrowingObjectLoss]
obj_particle_id: 2
obj_x_mul: [0.,-1.,0.]

seed: 100
torch_seed: 100
static_as_fixed: True
device_memory_fraction: 0.75